export const employees = [
  {
    id: 1,
    name: "Tanner Finsha",
    email: "Tanner.fisher@gmail.com",
    employeeId: "#23454GH6J7YT6",
    assignedLeads: 5,
    closedLeads: 2,
    status: "Active",
    avatar:
      "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 2,
    name: "Emeto Winner",
    email: "Emetowinner@gmail.com",
    employeeId: "#98345AGJH8IO9",
    assignedLeads: 3,
    closedLeads: 1,
    status: "Active",
    avatar: "EW",
  },
  {
    id: 3,
    name: "Tassy Omah",
    email: "Tassyomah@gmail.com",
    employeeId: "#32893HJDKLQ23",
    assignedLeads: 5,
    closedLeads: 0,
    status: "Inactive",
    avatar:
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 4,
    name: "James Muriel",
    email: "JamesMuriel@Aerten.finance",
    employeeId: "#87345JHGGH89",
    assignedLeads: 2,
    closedLeads: 0,
    status: "Inactive",
    avatar: "JM",
  },
  {
    id: 5,
    name: "Linda Ash",
    email: "linda.ash@company.com",
    employeeId: "#78654KJHG88",
    assignedLeads: 7,
    closedLeads: 5,
    status: "Active",
    avatar:
      "https://images.pexels.com/photos/1239297/pexels-photo-1239297.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 6,
    name: "Robert Finch",
    email: "r.finch@domain.com",
    employeeId: "#23459GHJ765U",
    assignedLeads: 4,
    closedLeads: 3,
    status: "Active",
    avatar: "RF",
  },
  {
    id: 7,
    name: "Sasha Grey",
    email: "sasha.grey@workplace.com",
    employeeId: "#90876JUIK987",
    assignedLeads: 6,
    closedLeads: 2,
    status: "Active",
    avatar: "SG",
  },
  {
    id: 8,
    name: "Kevin Stone",
    email: "kevin.stone@corp.com",
    employeeId: "#11983LKJH23D",
    assignedLeads: 2,
    closedLeads: 1,
    status: "Inactive",
    avatar:
      "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 9,
    name: "Isha Raj",
    email: "isha.raj@company.com",
    employeeId: "#98234KLJH32A",
    assignedLeads: 9,
    closedLeads: 6,
    status: "Active",
    avatar: "IR",
  },
  {
    id: 10,
    name: "Rajiv Kapoor",
    email: "rajiv.kapoor@corp.org",
    employeeId: "#67329KLJH99B",
    assignedLeads: 3,
    closedLeads: 1,
    status: "Inactive",
    avatar:
      "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 11,
    name: "Sara Lance",
    email: "sara.lance@startup.io",
    employeeId: "#24689KJJH32C",
    assignedLeads: 10,
    closedLeads: 9,
    status: "Active",
    avatar: "SL",
  },
  {
    id: 12,
    name: "Chris Evans",
    email: "chris.evans@domain.com",
    employeeId: "#23454CHS78YH",
    assignedLeads: 5,
    closedLeads: 4,
    status: "Active",
    avatar:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 13,
    name: "Emily Clarke",
    email: "emily.clarke@aerten.com",
    employeeId: "#90210DKSH99V",
    assignedLeads: 2,
    closedLeads: 2,
    status: "Active",
    avatar: "EC",
  },
  {
    id: 14,
    name: "Oliver Queen",
    email: "oliver.queen@green.com",
    employeeId: "#45782GHKJH77",
    assignedLeads: 7,
    closedLeads: 5,
    status: "Inactive",
    avatar:
      "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 15,
    name: "Barry Allen",
    email: "barry.allen@speed.com",
    employeeId: "#56289DKJS88H",
    assignedLeads: 3,
    closedLeads: 3,
    status: "Active",
    avatar: "BA",
  },
  {
    id: 16,
    name: "Diana Prince",
    email: "diana.prince@amazon.com",
    employeeId: "#76893LSKH12D",
    assignedLeads: 6,
    closedLeads: 6,
    status: "Active",
    avatar: "DP",
  },
  {
    id: 17,
    name: "Clark Kent",
    email: "clark.kent@dailyplanet.com",
    employeeId: "#23488LKJS88D",
    assignedLeads: 1,
    closedLeads: 0,
    status: "Inactive",
    avatar: "CK",
  },
  {
    id: 18,
    name: "Bruce Wayne",
    email: "bruce.wayne@waynecorp.com",
    employeeId: "#99888DKJS33G",
    assignedLeads: 5,
    closedLeads: 5,
    status: "Active",
    avatar:
      "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 19,
    name: "Natasha Romanoff",
    email: "natasha.romanoff@shield.com",
    employeeId: "#33455KJHH22N",
    assignedLeads: 8,
    closedLeads: 6,
    status: "Active",
    avatar: "NR",
  },
  {
    id: 20,
    name: "Steve Rogers",
    email: "steve.rogers@avengers.com",
    employeeId: "#66884KJSJ88R",
    assignedLeads: 2,
    closedLeads: 2,
    status: "Inactive",
    avatar: "SR",
  },
  {
    id: 21,
    name: "Wanda Maximoff",
    email: "wanda.maximoff@magic.com",
    employeeId: "#99887LKJD77W",
    assignedLeads: 4,
    closedLeads: 4,
    status: "Active",
    avatar: "WM",
  },
  {
    id: 22,
    name: "Peter Parker",
    email: "peter.parker@dailybugle.com",
    employeeId: "#44578KJH88Z",
    assignedLeads: 6,
    closedLeads: 5,
    status: "Active",
    avatar:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 23,
    name: "Nick Fury",
    email: "nick.fury@shield.com",
    employeeId: "#11223JHG77N",
    assignedLeads: 9,
    closedLeads: 8,
    status: "Active",
    avatar: "NF",
  },
  {
    id: 24,
    name: "Pepper Potts",
    email: "pepper.potts@starkindustries.com",
    employeeId: "#22990LKJH33P",
    assignedLeads: 4,
    closedLeads: 3,
    status: "Inactive",
    avatar: "PP",
  },
  {
    id: 25,
    name: "Shuri Wakanda",
    email: "shuri@wakanda.tech",
    employeeId: "#55555JHJ99S",
    assignedLeads: 7,
    closedLeads: 6,
    status: "Active",
    avatar:
      "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=100&h=100&fit=crop",
  },
  {
    id: 26,
    name: "Stephen Strange",
    email: "dr.strange@sanctum.com",
    employeeId: "#67890DFGH66T",
    assignedLeads: 10,
    closedLeads: 10,
    status: "Active",
    avatar: "SS",
  },
  {
    id: 27,
    name: "Loki Laufeyson",
    email: "loki@godofmischief.com",
    employeeId: "#11345LKJH78L",
    assignedLeads: 1,
    closedLeads: 0,
    status: "Inactive",
    avatar: "LL",
  },
  {
    id: 28,
    name: "Gamora Zen",
    email: "gamora@guardians.com",
    employeeId: "#99882JHG66G",
    assignedLeads: 3,
    closedLeads: 2,
    status: "Active",
    avatar: "GZ",
  },
];

export const locations = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const languages = [
  "Tamil",
  "Hindi",
  "English",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Marathi",
  "Gujarati",
];
